### ISSUE TITLE
Can't you publish code on Github?

### ISSUE THREAD

**Issue by DenisCarriere** [nokutu/mapillary#1]

**Comment by DenisCarriere** [comment]
Maybe your code is already on Github, but no one can't post Mapillary related issues on the Openstreetmap plugin repo.

https://github.com/openstreetmap/josm-plugins

**Comment by floscher** [comment]
The code is already on Github, see [floscher/josm-mapillary-plugin](//github.com/floscher/josm-mapillary-plugin).
However the issues regarding the code are tracked over at [the trac-instance for JOSM](https://josm.openstreetmap.de/query?status=assigned&status=closed&status=needinfo&status=new&status=reopened&component=Plugin+mapillary&desc=1&order=id).
If you want to contribute code, you can of course do that via GitHub pull requests in the abovementioned repo.

**Comment by DenisCarriere** [comment]
Thanks for the info! :)
