### ISSUE TITLE
Old "view in website" link

### ISSUE THREAD

**Issue by DenisCarriere** [nokutu/mapillary#2]
At the bottom right of the Image preview when you click **Edit on website** it sends you to the old URL schema:
### Old URL schema

http://www.mapillary.com/map/e/chGfvxpAl_fGbqU1RLX4Lg
### New URL schema

http://www.mapillary.com/map/im/chGfvxpAl_fGbqU1RLX4Lg/photo

**Comment by floscher** [comment]
No, it sends you to the edit page, which is still used in the new interface (on http://www.mapillary.com/map/im/chGfvxpAl_fGbqU1RLX4Lg/photo click on "Edit" and then on the button that says "Edit").

In my opinion that is currently the desired behaviour when clicking on "Edit on website".

The link that you propose would at the moment rather make sense if the link said "View on website".

If more edit functionality (additional to blur and traffic signs) is integrated in the viewer in the future, we could really link to the other URL.

cc @nokutu

**Comment by DenisCarriere** [comment]
You can't edit the blurs anymore in the "Edit on website", you must be in the "Image Viewer" mode.

In the Image Viewer mode you can simply click the edit tab and a drop down shows up with the available options of blur editing & traffic signs.

You need to be logged in to preview the Edit options in the normal viewer.

Seriously consider changing the URL, or ask some feedback from some Mapillary users. 

cc @nokutu

**Comment by floscher** [comment]
I asked the mapillary team about that yesterday. They told me, that there are no plans to abandon the edit-page. It has temporarily lost the capability of editing blurs and traffic signs, but these functions are only one click away (behind the "Edit blurring" button). And eventually this missing functionality will reappear on the edit-page:

> […] when we update the editor it will also have all the functionality that viewer has.
> Until then for detailed edits `/e/` route is the choice I'd say.
> I'll add some information that blurs and traffic signs could be edited directly in the viewer.
> I do understand that having this in both places is not optimal, but we have to stick to it until the overdue editor update.

So I still don't think, there is currently a need to change the URL of that link.

**Comment by DenisCarriere** [comment]
That's good news! OK I know that Mapillary have overhauled the viewer page, the Editor mode is up coming then.

Disregard my issue, the editor page would be the best place for the JOSM Mapillary plugin.

Thanks for inquiring :)
